package com.margelo.nitro.pressripple

import android.graphics.Color
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.view.View
import android.view.ViewGroup
import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip
import com.facebook.react.uimanager.UIManagerHelper
import com.margelo.nitro.NitroModules

/**
 * Nitro HybridObject — M3 Material ripple effect controller.
 *
 * Programmatically attaches a PressRippleView (Canvas overlay) to any host view
 * identified by its React Native view tag. No native view component registration
 * needed — the overlay is added directly to the Android view hierarchy.
 *
 * Thread model:
 *  - Nitro calls methods on the JS thread (JSI)
 *  - All Android view operations are dispatched to the main thread via mainHandler
 *
 * NOTE: HybridPressRippleSpec is generated by `npx nitrogen` from PressRipple.nitro.ts.
 * Run it once before building: cd react-native-press-ripple && npx nitrogen
 */
@Keep
@DoNotStrip
class HybridPressRipple : HybridPressRippleSpec() {

    private val mainHandler = Handler(Looper.getMainLooper())

    // The Canvas overlay view — null until attachToView() succeeds
    @Volatile private var rippleView: PressRippleView? = null

    // The host ViewGroup the overlay is attached to — kept to clean up the layout listener
    private var storedHostView: ViewGroup? = null

    // Syncs the overlay size whenever Fabric lays out the host view.
    // In Fabric (new arch), React Native calls view.layout(l,t,r,b) directly,
    // bypassing the Android measure/layout pass. MATCH_PARENT won't work because
    // Fabric doesn't trigger a layout pass for imperatively-added children.
    private val overlayLayoutSyncer = View.OnLayoutChangeListener { v, left, top, right, bottom, _, _, _, _ ->
        val overlay = rippleView ?: return@OnLayoutChangeListener
        val w = right - left
        val h = bottom - top
        if (overlay.width != w || overlay.height != h) {
            Log.d(TAG, "layout sync: overlay resized to ${w}x${h}")
            overlay.layout(0, 0, w, h)
        }
    }

    // ── Props ─────────────────────────────────────────────────────────────────

    override var color: String = "#40000000"
        set(value) {
            field = value
            val parsed = parseColor(value)
            mainHandler.post { rippleView?.setRippleColor(parsed) }
        }

    override var borderRadius: Double = 0.0
        set(value) {
            field = value
            val radius = value.toInt()
            mainHandler.post { rippleView?.setBorderRadius(radius) }
        }

    // ── Methods ───────────────────────────────────────────────────────────────

    /**
     * Find the native view by React tag, create a PressRippleView overlay,
     * and add it as the topmost child so it draws above the Pressable's content.
     *
     * Uses UIManagerHelper.getUIManagerForReactTag + resolveView — the correct
     * cross-architecture API that works in both Paper and Fabric (new arch).
     */
    override fun attachToView(hostViewTag: Double) {
        Log.d(TAG, "attachToView called with tag=$hostViewTag")
        mainHandler.post {
            val context = NitroModules.applicationContext
            if (context == null) {
                Log.e(TAG, "attachToView FAILED: applicationContext is null")
                return@post
            }
            val tag = hostViewTag.toInt()

            val uiManager = UIManagerHelper.getUIManagerForReactTag(context, tag)
            if (uiManager == null) {
                Log.e(TAG, "attachToView FAILED: UIManager not found for tag=$tag")
                return@post
            }

            val rawView = try {
                uiManager.resolveView(tag)
            } catch (e: Exception) {
                Log.e(TAG, "attachToView FAILED: resolveView threw for tag=$tag: ${e.message}")
                null
            }

            if (rawView == null) {
                Log.e(TAG, "attachToView FAILED: view not found for tag=$tag")
                return@post
            }

            val hostView = rawView as? ViewGroup
            if (hostView == null) {
                Log.e(TAG, "attachToView FAILED: view (${rawView::class.simpleName}) is NOT a ViewGroup for tag=$tag")
                return@post
            }

            Log.d(TAG, "attachToView SUCCESS: found ${hostView::class.simpleName} (${hostView.width}x${hostView.height}) for tag=$tag")

            // Remove stale overlay and listener from the previous host, if any
            storedHostView?.removeOnLayoutChangeListener(overlayLayoutSyncer)
            rippleView?.let { old -> (old.parent as? ViewGroup)?.removeView(old) }

            val overlay = PressRippleView(context).apply {
                setRippleColor(parseColor(this@HybridPressRipple.color))
                setBorderRadius(this@HybridPressRipple.borderRadius.toInt())
            }

            // Keep a reference so detachFromView() can remove the listener
            storedHostView = hostView

            // Listen for Fabric layout updates so the overlay always matches the host size.
            // Fabric calls view.layout(l,t,r,b) directly; the overlay won't be measured
            // or laid out by the Android system since it's not in React's view tree.
            hostView.addOnLayoutChangeListener(overlayLayoutSyncer)

            hostView.addView(overlay)
            rippleView = overlay

            // If the host is already laid out, size the overlay immediately
            if (hostView.width > 0 && hostView.height > 0) {
                overlay.layout(0, 0, hostView.width, hostView.height)
                Log.d(TAG, "attachToView: overlay sized immediately to ${hostView.width}x${hostView.height}")
            }

            Log.d(TAG, "attachToView: overlay added to ${hostView::class.simpleName}")
        }
    }

    /**
     * Remove the overlay from the view hierarchy and release the reference.
     */
    override fun detachFromView() {
        mainHandler.post {
            storedHostView?.removeOnLayoutChangeListener(overlayLayoutSyncer)
            storedHostView = null
            rippleView?.let { view ->
                (view.parent as? ViewGroup)?.removeView(view)
            }
            rippleView = null
        }
    }

    /**
     * Trigger a ripple at (x, y) in density-independent pixels.
     * JSI call is synchronous; animation dispatches to the UI thread.
     */
    override fun triggerRipple(x: Double, y: Double) {
        val view = rippleView
        if (view == null) {
            Log.e(TAG, "triggerRipple SKIPPED: rippleView is null (overlay not attached yet)")
            return
        }
        Log.d(TAG, "triggerRipple at ($x, $y), view=${view.width}x${view.height}")
        mainHandler.post {
            view.startRipple(x.toFloat(), y.toFloat())
        }
    }

    // ── Helper ────────────────────────────────────────────────────────────────

    companion object {
        private const val TAG = "PressRipple"
    }

    private fun parseColor(colorString: String): Int = try {
        Color.parseColor(colorString)
    } catch (e: IllegalArgumentException) {
        Color.parseColor("#40000000")
    }
}
