package com.margelo.nitro.pressripple

import android.graphics.Color
import android.os.Handler
import android.os.Looper
import android.view.View
import android.view.ViewGroup
import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip
import com.margelo.nitro.NitroModules

/**
 * Nitro HybridObject — M3 Material ripple effect controller.
 *
 * Programmatically attaches a PressRippleView (Canvas overlay) to any host view
 * identified by its React Native view tag. No native view component registration
 * needed — the overlay is added directly to the Android view hierarchy.
 *
 * Thread model:
 *  - Nitro calls methods on the JS thread (JSI)
 *  - All Android view operations are dispatched to the main thread via mainHandler
 *
 * NOTE: HybridPressRippleSpec is generated by `npx nitrogen` from PressRipple.nitro.ts.
 * Run it once before building: cd react-native-press-ripple && npx nitrogen
 */
@Keep
@DoNotStrip
class HybridPressRipple : HybridPressRippleSpec() {

    private val mainHandler = Handler(Looper.getMainLooper())

    // The Canvas overlay view — null until attachToView() succeeds
    @Volatile private var rippleView: PressRippleView? = null

    // ── Props ─────────────────────────────────────────────────────────────────

    override var color: String = "#40000000"
        set(value) {
            field = value
            val parsed = parseColor(value)
            mainHandler.post { rippleView?.setRippleColor(parsed) }
        }

    override var borderRadius: Double = 0.0
        set(value) {
            field = value
            val radius = value.toInt()
            mainHandler.post { rippleView?.setBorderRadius(radius) }
        }

    // ── Methods ───────────────────────────────────────────────────────────────

    /**
     * Find the native view by React tag, create a PressRippleView overlay,
     * and add it as the topmost child so it draws above the Pressable's content.
     *
     * React Native sets each view's Android ID equal to its React tag, so
     * decorView.findViewById(reactTag) reliably returns the correct view.
     */
    override fun attachToView(hostViewTag: Double) {
        mainHandler.post {
            val context = NitroModules.applicationContext ?: return@post
            val tag = hostViewTag.toInt()

            // Walk up from the window's decor view to find the host
            val activity = context.currentActivity ?: return@post
            val decorView = activity.window.decorView as? ViewGroup ?: return@post
            val hostView = decorView.findViewById<View>(tag) as? ViewGroup ?: return@post

            // Remove stale overlay if reattaching
            rippleView?.let { old -> (old.parent as? ViewGroup)?.removeView(old) }

            val overlay = PressRippleView(context).apply {
                layoutParams = ViewGroup.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT
                )
                // Apply current config
                setRippleColor(parseColor(this@HybridPressRipple.color))
                setBorderRadius(this@HybridPressRipple.borderRadius.toInt())
            }

            hostView.addView(overlay) // added last → renders on top of content
            rippleView = overlay
        }
    }

    /**
     * Remove the overlay from the view hierarchy and release the reference.
     */
    override fun detachFromView() {
        mainHandler.post {
            rippleView?.let { view ->
                (view.parent as? ViewGroup)?.removeView(view)
            }
            rippleView = null
        }
    }

    /**
     * Trigger a ripple at (x, y) in density-independent pixels.
     * JSI call is synchronous; animation dispatches to the UI thread.
     */
    override fun triggerRipple(x: Double, y: Double) {
        // Capture reference before posting to avoid null after detach
        val view = rippleView ?: return
        mainHandler.post {
            view.startRipple(x.toFloat(), y.toFloat())
        }
    }

    // ── Helper ────────────────────────────────────────────────────────────────

    private fun parseColor(colorString: String): Int = try {
        Color.parseColor(colorString)
    } catch (e: IllegalArgumentException) {
        Color.parseColor("#40000000")
    }
}
